### PR TITLE
Use syst.prop. value when loading properties from resource files

### PR DESCRIPTION
**Pull request by jhrcek**

### CODE REVIEW

**Comment by sutaakar** [comment]
Test failures caused by https://github.com/kiegroup/kie-cloud-tests/pull/269

**Comment by jakubschwan** [comment]
failures fixed by #270 (#269 was closed)

**Comment by jakubschwan** [comment]
jenkins retest this

**Comment by jakubschwan** [comment]
retest this please

**Comment by sutaakar** [comment]
Please cherrypick the changes to master branch

**Pull request merged**
