### PR TITLE
Framework for Kie cloud tests

### PR DESCRIPTION
**Pull request by sutaakar**
Currently supporting just OpenShift.
Implemented connectors for GitLab and GitHub for scenarios requiring external GIT repo.

Collaborative work with @jiripetrlik

### CODE REVIEW

**Comment by sutaakar** [comment]
Build failure caused by missing tests.

**Comment by psiroky** [comment]
Job fixed to not require test results as part of the build.

**Comment by sutaakar** [comment]
@jiripetrlik @psiroky Please review whenever you will have some time.

**Comment by triceo** [comment]
@ksuta Done.

**Comment by sutaakar** [comment]
@triceo Thanks

**Comment by sutaakar** [comment]
Added basic tests and instructions

**Comment by sutaakar** [comment]
@jiripetrlik Updated packages.

**Pull request merged**
