### PR TITLE
JBPM-6662: Scale to zero Workbench, KIE server and Kie router test

### PR DESCRIPTION
**Pull request by jakubschwan**

### CODE REVIEW

**Comment by jakubschwan** [comment]
PR was updated and can be merge after tests pass.
@sutaakar @jiripetrlik please, can you review this PR again

**Comment by jakubschwan** [comment]
retest this please

**Comment by sutaakar** [comment]
Test failures will be fixed by https://github.com/jboss-container-images/rhpam-7-openshift-image/pull/89

**Comment by jakubschwan** [comment]
retest this please

**Comment by sutaakar** [comment]
@jakubschwan Looks good

**Pull request merged**
