### PR TITLE
BAQE-1544: Enable checkstyle on Maven build

### PR DESCRIPTION
**Pull request by Sgitario**
JIRA: https://issues.redhat.com/browse/BAQE-1544

### CODE REVIEW

**Comment by Sgitario** [comment]
I think adding the checkstyle on maven build will make the PR reviews easier.
Wdyt @sutaakar and @jakubschwan ?

**Review by sutaakar — APPROVED** [review]

**Comment by sutaakar** [comment]
The Checkstyle validation was turned off as different people used different editors with own formatting styles.
I think it is ok to turn it on to see if such issues are still there.

**Comment by Sgitario** [comment]
> The Checkstyle validation was turned off as different people used different editors with own formatting styles.
> I think it is ok to turn it on to see if such issues are still there.

+1  For me, using the drools formatting style in Eclipse, fixed all of the formatting violations automatically. But let's see.

**Review by jakubschwan — APPROVED** [review]

**Comment by jakubschwan** [comment]
@Sgitario could you add Fromating section to README.md file and put there link to formatting style files https://github.com/kiegroup/droolsjbpm-build-bootstrap/tree/master/ide-configuration . In case someone have problems to pass the checkstyle step.

**Comment by Sgitario** [comment]
> @Sgitario could you add Fromating section to README.md file and put there link to formatting style files https://github.com/kiegroup/droolsjbpm-build-bootstrap/tree/master/ide-configuration . In case someone have problems to pass the checkstyle step.

Added

**Pull request merged**
